name: Test and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-lint:
    name: Test and Lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install C/C++ tools
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt update
              sudo apt install ninja-build -y
          elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install ninja
              choco install mingw
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install ninja
              brew install llvm
              ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
              ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Ruff
        run: pip install ruff

      - name: Run tests
        run: python ./test.py
